sudo: required

env:
  - DOCKER_FILE_PATH=./elasticsearch/6.1.1/ TAG=es6.1.1
  - DOCKER_FILE_PATH=./elasticsearch/6.2.4/ TAG=es6.2.4
  - DOCKER_FILE_PATH=./python-gis/3.6/ TAG=py3.6
  - DOCKER_FILE_PATH=./python-gis/3.6/ci/ TAG=py3.6-ci
  - DOCKER_FILE_PATH=./python-gis-node/python3/circle-ci/ TAG=py3.6-node-ci

services:
  - docker

script:
  - docker build -t founders4schools/dockerfiles:$TAG $DOCKER_FILE_PATH

notifications:
  slack:
    rooms:
      - f4s:u17h2Cc7RhhHNtypnAu7jbgY#dev
    on_success: change
    on_failure: always
  email: false

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
